glowing-octo-batman: MapViewer Class Reference
MapViewer Class Reference
#include <MapViewer.h>
Public Member Functions
MapViewer (Draw *drawer, GameManager *gameManager)
Creates the map viewer.
virtual ~MapViewer ()
void update (std::string input)
Updates the MapViewer. It gives an suitable output based on the users input, writes an title into the screen and executed the map render method. It also displays an description of the current map field, the player is standing on.
void notified ()
Private Member Functions
bool executeInput (std::string input)
Analyses the input of the user. If it matches with an RegEx, the fitting action will be executed.
void renderImage ()
Renders the map with all its fanciness.
std::string getRowOf (char field, int row)
Returns a specific row of an image (e.g. village or forest).
std::string getFieldDescription (char field)
Returns an description of the field the player stand on.
Private Attributes
int _selectedField
char _selectedFieldChar
std::string _mapGraphics [5][3]
SubMapViewer_Village * _subMap
Additional Inherited Members
Public Attributes inherited from GameScreen
Draw * _drawer
Protected Attributes inherited from GameScreen
GameManager * _gameManager
Detailed Description
Definition at line 11 of file MapViewer.h.
Constructor & Destructor Documentation
MapViewer::MapViewer (Draw * drawer, GameManager * gameManager)
Creates the map viewer.
Parameters
drawer Draw The drawer reference.
gameManager GameManager* The pointer to a game manager.
Definition at line 14 of file MapViewer.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _mapGraphics, _selectedField, _selectedFieldChar, _subMap, and Draw::getRawMap().
MapViewer::~MapViewer () virtual
Definition at line 44 of file MapViewer.cpp.
Member Function Documentation
bool MapViewer::executeInput (std::string input) private virtual
Analyses the input of the user. If it matches with an RegEx, the fitting action will be executed.
Parameters
input std::string The users input.
Returns
bool True if something has been executed.
Implements GameScreen.
Definition at line 81 of file MapViewer.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _selectedField, _selectedFieldChar, _subMap, Observable::attach(), GameManager::changeGameScreen(), and Draw::getRawMap().
Referenced by update().
std::string MapViewer::getFieldDescription (char field) private
Returns an description of the field the player stand on.
Parameters
field char The field char (v, f, ...).
Returns
std::string The description.
Definition at line 343 of file MapViewer.cpp.
Referenced by update().
std::string MapViewer::getRowOf (char field, int row) private
Returns a specific row of an image (e.g. village or forest).
Parameters
field char The field char (v for village, f for forest, ...).
row int The row of the image (between 0 and 2).
Returns
std::string The row as string.
Definition at line 316 of file MapViewer.cpp.
References _mapGraphics.
Referenced by renderImage().
void MapViewer::notified () virtual
Implements Observer.
Definition at line 363 of file MapViewer.cpp.
References GameScreen::_gameManager, _subMap, and GameManager::changeGameScreen().
void MapViewer::renderImage () private
Renders the map with all its fanciness.
Returns
void
Definition at line 133 of file MapViewer.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _selectedField, Draw::getRawMap(), getRowOf(), and GameManager::print().
Referenced by update().
void MapViewer::update (std::string input) virtual
Updates the MapViewer. It gives an suitable output based on the users input, writes an title into the screen and executed the map render method. It also displays an description of the current map field, the player is standing on.
Parameters
input std::string The users input.
Returns
void
Implements GameScreen.
Definition at line 58 of file MapViewer.cpp.
References GameScreen::_gameManager, _selectedFieldChar, _subMap, executeInput(), getFieldDescription(), GameManager::print(), GameManager::printText(), renderImage(), and SubMapViewer_Village::update().
Member Data Documentation
std::string MapViewer::_mapGraphics[5][3] private
Definition at line 15 of file MapViewer.h.
Referenced by getRowOf(), and MapViewer().
int MapViewer::_selectedField private
Definition at line 13 of file MapViewer.h.
Referenced by executeInput(), MapViewer(), and renderImage().
char MapViewer::_selectedFieldChar private
Definition at line 14 of file MapViewer.h.
Referenced by executeInput(), MapViewer(), and update().
SubMapViewer_Village* MapViewer::_subMap private
Definition at line 16 of file MapViewer.h.
Referenced by executeInput(), MapViewer(), notified(), and update().
The documentation for this class was generated from the following files:
MapViewer.h
MapViewer.cpp