glowing-octo-batman: Story Class Reference
Story Class Reference
#include <Story.h>
Public Member Functions
Story (std::string, std::string, GameManager *)
virtual ~Story ()
std::string getNextText ()
std::string answerChosen (std::string)
void setNextText (std::string)
std::string getCurrentSentence ()
void print ()
Private Member Functions
void loadStory (std::string)
std::vector< std::string > splitString (std::string, char)
void checkAnswers ()
std::vector< std::string > getAllAnswerKeys (std::string)
Private Attributes
std::map< std::map
< std::string, std::string >
, std::string > _next
std::map< std::string,
std::map< std::string,
std::string > > _answers
std::map< std::string,
std::string > _messages
std::vector< std::string > _sentences
std::string _currentSentence
GameManager * _gameManager
Detailed Description
Definition at line 10 of file Story.h.
Constructor & Destructor Documentation
Story::Story (std::string storyName, std::string firstSentence, GameManager * gameManager)
Definition at line 12 of file Story.cpp.
References _currentSentence, _gameManager, and loadStory().
Story::~Story () virtual
Definition at line 19 of file Story.cpp.
Member Function Documentation
std::string Story::answerChosen (std::string answer)
This method will give you the next sentence depending on the users answer.
Parameters
answer The answer of the user.
Returns
The name of the next sentence.
Definition at line 40 of file Story.cpp.
References _currentSentence, _next, and getAllAnswerKeys().
Referenced by StoryView::executeInput().
void Story::checkAnswers () private
Checks if every answer has its next block.
Definition at line 236 of file Story.cpp.
References _gameManager, _next, _sentences, getAllAnswerKeys(), and GameManager::printText().
Referenced by loadStory().
std::vector< std::string > Story::getAllAnswerKeys (std::string sentence) private
Gets a list of all answer keys in the given sentence.
Parameters
sentence The sentence which answers you want to know.
Returns
The list of answers.
Definition at line 258 of file Story.cpp.
References _answers.
Referenced by answerChosen(), checkAnswers(), and print().
std::string Story::getCurrentSentence ()
Gets the current sentence of the story.
Returns
Definition at line 66 of file Story.cpp.
References _currentSentence.
Referenced by StoryView::executeInput(), and StoryView::getCurrentSentence().
std::string Story::getNextText ()
Gets the next sentence.
Returns
The next gamescreen when the user presses ENTER. If he has to choose between answers, the reult will be the current sentence.
Definition at line 27 of file Story.cpp.
References _currentSentence, and _next.
Referenced by StoryView::executeInput().
void Story::loadStory (std::string storyName) private
Load a story. The story has to be a .txt file and the extension must not be part of the parameter.
Parameters
storyName The name of the story.
Definition at line 90 of file Story.cpp.
References _answers, _gameManager, _messages, _next, _sentences, checkAnswers(), GameManager::printText(), and splitString().
Referenced by Story().
void Story::print ()
Prints the message of the story.
Definition at line 73 of file Story.cpp.
References _answers, _currentSentence, _gameManager, _messages, getAllAnswerKeys(), and GameManager::printText().
Referenced by StoryView::StoryView(), and StoryView::update().
void Story::setNextText (std::string nextSentence)
This will set the new sentence.
Parameters
nextSentence The new sentence.
Definition at line 58 of file Story.cpp.
References _currentSentence.
Referenced by StoryView::executeInput().
std::vector< std::string > Story::splitString (std::string str, char delimiter) private
Splits a string by the given delimiter.
Parameters
str The string.
delimiter The delimiter to split by.
Returns
All parts after splitting.
Definition at line 282 of file Story.cpp.
Referenced by loadStory().
Member Data Documentation
std::map<std::string, std::map<std::string, std::string> > Story::_answers private
Definition at line 13 of file Story.h.
Referenced by getAllAnswerKeys(), loadStory(), and print().
std::string Story::_currentSentence private
Definition at line 16 of file Story.h.
Referenced by answerChosen(), getCurrentSentence(), getNextText(), print(), setNextText(), and Story().
GameManager* Story::_gameManager private
Definition at line 17 of file Story.h.
Referenced by checkAnswers(), loadStory(), print(), and Story().
std::map<std::string, std::string> Story::_messages private
Definition at line 14 of file Story.h.
Referenced by loadStory(), and print().
std::map<std::map<std::string, std::string>, std::string> Story::_next private
Definition at line 12 of file Story.h.
Referenced by answerChosen(), checkAnswers(), getNextText(), and loadStory().
std::vector<std::string> Story::_sentences private
Definition at line 15 of file Story.h.
Referenced by checkAnswers(), and loadStory().
The documentation for this class was generated from the following files:
Story.h
Story.cpp