glowing-octo-batman: Observable Class Reference
Observable Class Reference
#include <Observable.h>
Public Member Functions
void attach (Observer *observer)
void notify ()
Private Attributes
list< Observer * > observers
Detailed Description
Definition at line 9 of file Observable.h.
Member Function Documentation
void Observable::attach (Observer * observer)
Attaches an observer to the list of all observers of this class.
Parameters
observer The observer
Definition at line 10 of file Observable.cpp.
Referenced by MapViewer::executeInput().
void Observable::notify ()
Notifies all observers about a change.
Definition at line 18 of file Observable.cpp.
Referenced by SubMapViewer_Village::executeInput(), and StoryView::executeInput().
Member Data Documentation
list<Observer*> Observable::observers private
Definition at line 15 of file Observable.h.
The documentation for this class was generated from the following files:
Observable.h
Observable.cpp