glowing-octo-batman: MainMenu Class Reference
MainMenu Class Reference
#include <MainMenu.h>
Public Member Functions
MainMenu (Draw *drawer, GameManager *gameManager)
Creates the main menu.
virtual ~MainMenu ()
void update (std::string input)
The update method for the MainMenu. This method prints the main menu image onto the screen and creates an output based on the users input.
Private Member Functions
bool executeInput (std::string input)
The given input will be analysed. If the input is usable (matching to an RegEx), a fitting operation will be executed.
Private Attributes
StoryView * _introView
Additional Inherited Members
Public Attributes inherited from GameScreen
Draw * _drawer
Protected Attributes inherited from GameScreen
GameManager * _gameManager
Detailed Description
Definition at line 7 of file MainMenu.h.
Constructor & Destructor Documentation
MainMenu::MainMenu (Draw * drawer, GameManager * gameManager)
Creates the main menu.
Parameters
drawer Draw The drawer reference.
gameManager GameManager* The pointer to a game manager.
Definition at line 15 of file MainMenu.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _introView, Draw::printMainMenuImage(), and Draw::printMainMenuText().
MainMenu::~MainMenu () virtual
Definition at line 24 of file MainMenu.cpp.
Member Function Documentation
bool MainMenu::executeInput (std::string input) private virtual
The given input will be analysed. If the input is usable (matching to an RegEx), a fitting operation will be executed.
Parameters
input std::string The users inout.
Returns
bool True if an action has been executed.
Implements GameScreen.
Definition at line 53 of file MainMenu.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _introView, GameManager::changeGameScreen(), GameManager::clearScreen(), StoryView::getCurrentSentence(), GameManager::printText(), and StoryView::update().
Referenced by update().
void MainMenu::update (std::string input) virtual
The update method for the MainMenu. This method prints the main menu image onto the screen and creates an output based on the users input.
Parameters
input std::string The input from the user.
Returns
void
Implements GameScreen.
Definition at line 35 of file MainMenu.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, _introView, executeInput(), Draw::printMainMenuImage(), Draw::printMainMenuText(), GameManager::printText(), and StoryView::update().
Member Data Documentation
StoryView* MainMenu::_introView private
Definition at line 16 of file MainMenu.h.
Referenced by executeInput(), MainMenu(), and update().
The documentation for this class was generated from the following files:
MainMenu.h
MainMenu.cpp