glowing-octo-batman: Draw Class Reference
Draw Class Reference
#include <Draw.h>
Public Member Functions
Draw (GameManager *)
virtual ~Draw ()
void loadAll ()
Loads all image and map files.
void printMainMenuImage ()
Prints the image of the main menu onto the screen.
void printMainMenuText ()
Prints the text of the main menu.
std::string getRawMap ()
Returns the raw map with its field chars.
Private Attributes
std::string _titleImage
std::string _map_raw
std::string _map_processed
GameManager * _gameManager
Detailed Description
Definition at line 8 of file Draw.h.
Constructor & Destructor Documentation
Draw::Draw (GameManager * gameManager)
Definition at line 6 of file Draw.cpp.
References _gameManager.
Draw::~Draw () virtual
Definition at line 11 of file Draw.cpp.
Member Function Documentation
std::string Draw::getRawMap ()
Returns the raw map with its field chars.
Returns
std::string The raw map.
Definition at line 86 of file Draw.cpp.
References _map_raw.
Referenced by MapViewer::executeInput(), MapViewer::MapViewer(), and MapViewer::renderImage().
void Draw::loadAll ()
Loads all image and map files.
Returns
void
Definition at line 21 of file Draw.cpp.
References _map_raw, and _titleImage.
Referenced by GameManager::start().
void Draw::printMainMenuImage ()
Prints the image of the main menu onto the screen.
Returns
void
Definition at line 66 of file Draw.cpp.
References _gameManager, _titleImage, and GameManager::printText().
Referenced by MainMenu::MainMenu(), and MainMenu::update().
void Draw::printMainMenuText ()
Prints the text of the main menu.
Returns
void
Definition at line 76 of file Draw.cpp.
References _gameManager, and GameManager::printText().
Referenced by MainMenu::MainMenu(), and MainMenu::update().
Member Data Documentation
GameManager* Draw::_gameManager private
Definition at line 11 of file Draw.h.
Referenced by Draw(), printMainMenuImage(), and printMainMenuText().
std::string Draw::_map_processed private
Definition at line 10 of file Draw.h.
std::string Draw::_map_raw private
Definition at line 10 of file Draw.h.
Referenced by getRawMap(), and loadAll().
std::string Draw::_titleImage private
Definition at line 10 of file Draw.h.
Referenced by loadAll(), and printMainMenuImage().
The documentation for this class was generated from the following files:
Draw.h
Draw.cpp