glowing-octo-batman: GameManager Class Reference
GameManager Class Reference
#include <GameManager.h>
Public Member Functions
GameManager ()
virtual ~GameManager ()
void start ()
Starts the game manager. This will also execute the main game loop. This method also deals with input and will pass it on to the game screens.
void changeGameScreen (GameScreen *newScreen)
Replaces the current game screen with a new one.
void clearScreen ()
Will clear the buffer so the next draw (executing the readLine method) will clear the screen.
void print (std::string)
void printText (std::string)
Private Member Functions
std::string readLine ()
This will display the "~$>" string for the console-like input and also will read it.
void fillScreen ()
std::string printPart (std::string)
int getLength (std::string)
int countSubstring (std::string, std::string)
Private Attributes
Draw * _drawer
GameScreen * _gameScreen
GameScreen * _newGameScreen
std::string _output
Detailed Description
Definition at line 9 of file GameManager.h.
Constructor & Destructor Documentation
GameManager::GameManager ()
Definition at line 30 of file GameManager.cpp.
References _output.
GameManager::~GameManager () virtual
Definition at line 39 of file GameManager.cpp.
Member Function Documentation
void GameManager::changeGameScreen (GameScreen * newGameScreen)
Replaces the current game screen with a new one.
Parameters
newGameScreen GameScreen* The new game screen as pointer.
Returns
void
Definition at line 97 of file GameManager.cpp.
References _newGameScreen.
Referenced by MainMenu::executeInput(), MapViewer::executeInput(), and MapViewer::notified().
void GameManager::clearScreen ()
Will clear the buffer so the next draw (executing the readLine method) will clear the screen.
Returns
void
Definition at line 107 of file GameManager.cpp.
References _output.
Referenced by MainMenu::executeInput(), and start().
int GameManager::countSubstring (std::string str, std::string sub) private
Count the amount of a specific substring in a text.
Parameters
str The text.
sub The substring to count.
Returns
The amount of the substring.
Definition at line 234 of file GameManager.cpp.
Referenced by getLength().
void GameManager::fillScreen () private
Fills the screen with '
' characters so that the input line is at the very bottom and so that you can't see anything from the old screen.
Definition at line 247 of file GameManager.cpp.
References _output.
Referenced by start().
int GameManager::getLength (std::string str) private
Calculates the length of a string considering formatting stuff like \033[31m.
Parameters
str The string.
Returns
The amount of character (=length).
Definition at line 198 of file GameManager.cpp.
References countSubstring().
Referenced by printPart().
void GameManager::print (std::string output)
Puts a text into the buffer.
Parameters
output The text.
Definition at line 121 of file GameManager.cpp.
References _output.
Referenced by MapViewer::renderImage(), and MapViewer::update().
std::string GameManager::printPart (std::string output) private
This Method will make automatic line breaks into the text.
Parameters
output The text.
Returns
Formatted line. If the line does not need any line breaks "" will be returned.
Definition at line 161 of file GameManager.cpp.
References _output, and getLength().
Referenced by printText().
void GameManager::printText (std::string output)
Puts a text into the buffer and does automatic line breaks. This does not work with formatting stuff like \033[31m stuff and so on. This method cuts the text by the '
' character and calls the printPart() method for each part.
Parameters
output The text.
Definition at line 130 of file GameManager.cpp.
References _output, and printPart().
Referenced by Story::checkAnswers(), MainMenu::executeInput(), Story::loadStory(), Story::print(), Draw::printMainMenuImage(), Draw::printMainMenuText(), MainMenu::update(), and MapViewer::update().
std::string GameManager::readLine () private
This will display the "~$>" string for the console-like input and also will read it.
Returns
std:: string The users input.
Definition at line 82 of file GameManager.cpp.
References _output.
Referenced by start().
void GameManager::start ()
Starts the game manager. This will also execute the main game loop. This method also deals with input and will pass it on to the game screens.
Returns
void
Definition at line 50 of file GameManager.cpp.
References _drawer, _gameScreen, _newGameScreen, clearScreen(), fillScreen(), Draw::loadAll(), readLine(), and GameScreen::update().
Member Data Documentation
Draw* GameManager::_drawer private
Definition at line 11 of file GameManager.h.
Referenced by start().
GameScreen* GameManager::_gameScreen private
Definition at line 12 of file GameManager.h.
Referenced by start().
GameScreen * GameManager::_newGameScreen private
Definition at line 12 of file GameManager.h.
Referenced by changeGameScreen(), and start().
std::string GameManager::_output private
Definition at line 13 of file GameManager.h.
Referenced by clearScreen(), fillScreen(), GameManager(), print(), printPart(), printText(), and readLine().
The documentation for this class was generated from the following files:
GameManager.h
GameManager.cpp