glowing-octo-batman: SubMapViewer_Village Class Reference
SubMapViewer_Village Class Reference
#include <SubMapViewer_Village.h>
Public Member Functions
SubMapViewer_Village (Draw *drawer, GameManager *gameManager)
Creates a SubMapViewer for the village.
virtual ~SubMapViewer_Village ()
void update (std::string input)
Updates the MapViewer. It gives an suitable output based on the users input, writes an title into the screen and executed the submap render method.
Public Member Functions inherited from Observable
void attach (Observer *observer)
void notify ()
Private Member Functions
bool executeInput (std::string input)
Executes/interpretes the users input.
Private Attributes
bool _isActive
Additional Inherited Members
Public Attributes inherited from GameScreen
Draw * _drawer
Protected Attributes inherited from GameScreen
GameManager * _gameManager
Detailed Description
Definition at line 8 of file SubMapViewer_Village.h.
Constructor & Destructor Documentation
SubMapViewer_Village::SubMapViewer_Village (Draw * drawer, GameManager * gameManager)
Creates a SubMapViewer for the village.
Parameters
drawer Draw The drawer reference.
gameManager GameManager* The pointer to a game manager.
Definition at line 13 of file SubMapViewer_Village.cpp.
References GameScreen::_drawer, GameScreen::_gameManager, and _isActive.
SubMapViewer_Village::~SubMapViewer_Village () virtual
Definition at line 20 of file SubMapViewer_Village.cpp.
Member Function Documentation
bool SubMapViewer_Village::executeInput (std::string input) private virtual
Executes/interpretes the users input.
Parameters
input std::string The users input.
Returns
bool True when the input has been executed.
Implements GameScreen.
Definition at line 45 of file SubMapViewer_Village.cpp.
References Observable::notify().
Referenced by update().
void SubMapViewer_Village::update (std::string input) virtual
Updates the MapViewer. It gives an suitable output based on the users input, writes an title into the screen and executed the submap render method.
Parameters
input std::string The users input.
Returns
void
Implements GameScreen.
Definition at line 34 of file SubMapViewer_Village.cpp.
References executeInput().
Referenced by MapViewer::update().
Member Data Documentation
bool SubMapViewer_Village::_isActive private
Definition at line 10 of file SubMapViewer_Village.h.
Referenced by SubMapViewer_Village().
The documentation for this class was generated from the following files:
SubMapViewer_Village.h
SubMapViewer_Village.cpp