glowing-octo-batman: StoryView Class Reference
StoryView Class Reference
#include <StoryView.h>
Public Member Functions
StoryView (std::string, std::string, GameManager *)
virtual ~StoryView ()
void update (std::string)
std::string getCurrentSentence ()
Public Member Functions inherited from Observable
void attach (Observer *observer)
void notify ()
Private Member Functions
bool executeInput (std::string)
Private Attributes
GameManager * _gameManager
Story * _story
Additional Inherited Members
Public Attributes inherited from GameScreen
Draw * _drawer
Protected Attributes inherited from GameScreen
GameManager * _gameManager
Detailed Description
Definition at line 10 of file StoryView.h.
Constructor & Destructor Documentation
StoryView::StoryView (std::string storyName, std::string firstSentence, GameManager * gameManager)
Creates a new view for a story.
Parameters
storyName The name of the story (=name of the file with the story)
firstSentence The name of the first sentence.
gameManager The game manager.
Definition at line 11 of file StoryView.cpp.
References _story, and Story::print().
StoryView::~StoryView () virtual
Definition at line 16 of file StoryView.cpp.
Member Function Documentation
bool StoryView::executeInput (std::string) private virtual
Implements GameScreen.
Definition at line 25 of file StoryView.cpp.
References _story, Story::answerChosen(), Story::getCurrentSentence(), Story::getNextText(), Observable::notify(), and Story::setNextText().
Referenced by update().
std::string StoryView::getCurrentSentence ()
Definition at line 42 of file StoryView.cpp.
References _story, and Story::getCurrentSentence().
Referenced by MainMenu::executeInput().
void StoryView::update (std::string) virtual
Implements GameScreen.
Definition at line 20 of file StoryView.cpp.
References _story, executeInput(), and Story::print().
Referenced by MainMenu::executeInput(), and MainMenu::update().
Member Data Documentation
GameManager* StoryView::_gameManager private
Definition at line 12 of file StoryView.h.
Story* StoryView::_story private
Definition at line 13 of file StoryView.h.
Referenced by executeInput(), getCurrentSentence(), StoryView(), and update().
The documentation for this class was generated from the following files:
StoryView.h
StoryView.cpp